### ISSUE TITLE
Text gets selected on single tap instead of long-press on mobile

### ISSUE THREAD

**Issue by 3-stardust-7** [Pallavi-Madhu/Surgicare#58]
**Description**:
- On mobile devices, tapping on text in the app causes it to be selected immediately, unlike the standard behavior on most websites where a long-press is required. This leads to unintended text selections during normal - interactions.
- Clicking on images also causes them to be selected, which is not typical behavior and feels unintentional on touch devices.

**Expected Behavior**:
- Text should only become selectable after a long-press, like in most modern mobile websites.
- unless the user is deliberately trying to download or interact with them. Tapping an image should not trigger selection handles or blue outlines.

**Possible Cause**:
CSS rule like `user-select: text`  might be applied globally or to specific elements
touch-action or other JavaScript interference may be altering the default behavior

 **Proposed Fix:**

Add the following CSS to disable selection and dragging on images:

```css
img {
  user-select: none;
  -webkit-user-drag: none;
}
```

Optionally, target only touch devices using a media query:

```css
@media (pointer: coarse) {
  img {
    user-select: none;
    -webkit-user-drag: none;
  }
}
```

---

For fixing text selection behavior:

```css
* {
  user-select: none;
}

.text, p, h1, h2, span {
  user-select: auto;
}
```
